# ==============================================================
# VectorForge: NASA Space Biology Knowledge Engine
# Author: projectfong
# ==============================================================

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: vectorforge-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-spacebio}
      POSTGRES_USER: ${POSTGRES_USER:-spaceapps}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-spaceapps}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-spaceapps} -d ${POSTGRES_DB:-spacebio}"]
      interval: 5s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:v1.15.5
    container_name: vectorforge-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: vectorforge-backend
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: vectorforge-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
    restart: unless-stopped

volumes:
  pgdata:
  qdrant_storage:
